import { fail } from '../core';
import { Context } from '../../../src/parser/common';

fail('Miscellaneous - Early errors', [
  ['{ a = 0 });', Context.Empty],
  ['(...a)', Context.Empty],
  [`(a, ...b)`, Context.Empty],
  ['(((a, ...b)))', Context.Empty],
  ['0++', Context.Empty],
  ['({a: 0} = 0);', Context.Empty],
  ['({a(b){}} = 0)', Context.Empty],
  ['"use strict"; ({arguments = 1} = 2);', Context.Empty],
  [`[0] = 0;`, Context.Empty],
  [`0 = 0;`, Context.Empty],
  [`({a}) = 0;`, Context.Empty],
  [`([a]) = 0;`, Context.Empty],
  [`({a} += 0);`, Context.Empty],
  [`[a] *= 0;`, Context.Empty],
  [`0 /= 0;`, Context.Empty],
  [`[...{a: 0}] = 0;`, Context.Empty],
  [`[...[0]] = 0;`, Context.Empty],
  [`[...0] = 0;`, Context.Empty],
  ['a\\u{0}', Context.Empty],
  ['a\\u0000', Context.Empty],
  ['\\u{0}', Context.Empty],
  ['[...new a] = 0;', Context.Empty],
  ['for(([0]) of 0);', Context.Empty],
  ['for((0) of 0);', Context.Empty],
  [`/./\\u{69}`, Context.Empty],
  ["'use strict'; +implements;", Context.Empty],
  ["'use strict'; let:0;", Context.Empty],
  ["'use strict'; +yield;", Context.Empty],
  ["!{ get a() { 'use strict'; +let; } }", Context.Empty],
  ['class let {}', Context.Empty],
  ['class l\\u{65}t {}', Context.Empty],
  ['(class yield {})', Context.Empty],
  ['({ a(){ super(); } });', Context.Empty],
  ['"use strict"; ([yield] = a)', Context.Empty],
  ['class a extends b { constructor() { !{*constructor() { super(); }}; } }', Context.Empty],
  ['"use strict"; !function* arguments(){}', Context.Empty],
  ["'use strict'; delete ((a));", Context.Empty],
  ['!function(a){ super.b }', Context.Empty],
  [`async function a(b = await (0)) {}`, Context.Empty],
  ['(async function(b = await (0)) {})', Context.Empty],
  ['({ async a(b = await (0)) {} })', Context.Empty],
  ['(class { async constructor(){} })', Context.Empty],
  ['\\u0000', Context.Empty],
  ['\\u{0}', Context.Empty],
  ['a\\u0000', Context.Empty],
  ['\\u{110000}', Context.Empty],
  ['\\u{FFFFFFF}', Context.Empty],
  ['function f(a = super.b){}', Context.Empty],
  ['!function f(a = super[0]){}', Context.Empty],
  ['!function(a = super.b){}', Context.Empty],
  ['function f(a){ super.b }', Context.Empty],
  ['class a { b(eval){} };', Context.Empty],
  ['!{ a() { function* f(){ super.b(); } } };', Context.Empty],
  ['class A { constructor() { {{ (( super() )); }} } }', Context.Empty],
  ['class A { constructor() { super(); } }', Context.Empty],
  ['class A { *constructor(){} }', Context.Empty],
  ['class A extends B { static prototype(){} }', Context.Empty],
  ['class A extends B { static set prototype(a) {} }', Context.Empty],
  ["function a([]){'use strict';}", Context.Empty],
  ['({ a = 0 });', Context.Empty],
  ['(...a)', Context.Empty],
  ['(a, ...b)', Context.Empty],
  ['(((...a)))', Context.Empty],
  ['(((a, ...b)))', Context.Empty],
  ['0++', Context.Empty],
  ['0--', Context.Empty],
  ['++0', Context.Empty],
  ['--0', Context.Empty],
  ['({a: 0} = 0);', Context.Empty],
  ['({get a(){}} = 0)', Context.Empty],
  ['({set a(b){}} = 0)', Context.Empty],
  ['({a(b){}} = 0)', Context.Empty],
  ['[0] = 0;', Context.Empty],
  ['0 = 0;', Context.Empty],
  ['"use strict"; +yield;', Context.Empty],
  ['"use strict"; yield:;', Context.Empty],
  ['"use strict"; +protected:0;', Context.Empty],
  ['"use strict"; +yield:0;', Context.Empty],
  ['"use strict"; +async:0;', Context.Empty],
  ['"use strict"; function a([yield]){}', Context.Empty],
  ['"use strict"; function a({yield}){}', Context.Empty],
  ['"use strict";  function a({yield=0}){}', Context.Empty],
  ['"use strict"; function a({a:yield}){}', Context.Empty],
  ['"use strict"; function a([yield,...a]){}', Context.Empty],
  ['"use strict"; class A {set a(yield){}}', Context.Empty],
  ['const a;', Context.Empty],
  ["const a, b = 0;'", Context.Empty],
  ['const a = 0, b;', Context.Empty],
  ['{ const a; }', Context.Empty],
  ['function f(){ const a; }', Context.Empty],
  ['for(const a;;);', Context.Empty],
  ['for(const a = 0, b;;);', Context.Empty],
  ['for(const let in 0);', Context.Empty],
  ['for(let let of 0);', Context.Empty],
  ['for(const let of 0);', Context.Empty],
  ['{ continue; }', Context.Empty],
  ['continue', Context.Empty],
  ['if(0) continue;', Context.Empty],
  ['while(1) !function(){ break; };', Context.Empty],
  ['while(1) !function(){ continue; };', Context.Empty],
  ['({ a(){ super(); } });', Context.Empty],
  ['for(const a = 1, b;;);', Context.Empty],
  ['for([0] of 0);', Context.Empty],
  ['[a] *= 0;', Context.Empty],
  ['let a, b, c, let;', Context.Empty],
  ['"use strict"; +yield', Context.Empty],
  ['/[a-z]/z', Context.Empty],
  [
    `var af = x
            => x;`,
    Context.Empty
  ],
  ['async function a(k = super.prop) { }', Context.Empty],
  ['(async function(k = super.prop) {})', Context.Empty],
  ['(async function a(k = super.prop) {})', Context.Empty],
  ['async function a() { super.prop(); }', Context.Empty],
  ['(async function a() { super.prop(); })', Context.Empty],
  ['(async function a(k = super()) {})', Context.Empty],
  ['(async function a() { super(); })', Context.Empty],
  ['(async function a(k = await 3) {})', Context.Empty],
  ['async function a(k = await 3) {}', Context.Empty],
  ['"use strict" var af = (yield) => 1;', Context.Empty],
  ['({set a(b){}} = 0)', Context.Empty],
  ['for(const a;;);', Context.Empty],
  [`"use strict"; var af = package => 1;`, Context.Empty],
  ['function a() { "use strict"; var implements; }', Context.Empty],
  ["function a([yield,...a]){ 'use strict'; }", Context.Empty],
  ['function* a(){ function* b({c = yield}){} }', Context.Empty],
  ["function a() { 'use strict'; let = 1; }", Context.Empty],
  ['class a extends b { c() { function d(c = super.e()){} } }', Context.Empty],
  [` /./ii`, Context.Empty],
  [`(a, ...b)`, Context.Empty],
  [' for(const a = 1, let = 2;;);', Context.Empty],
  [` function a() { "use strict"; private = 1; }`, Context.Empty],
  ['({ a(){ super(); } });', Context.Empty],
  ['for(const a;;);', Context.Empty],
  [`"use strict"; for (a in let) {}`, Context.Empty],
  ['for({a: 0} of 0);', Context.Empty],
  ['b: break a;', Context.Empty],
  ['let a, let = 0;', Context.Empty],
  ['let a, let;', Context.Empty],
  ['for(let a, let;;);', Context.Empty],
  ['"use strict"; +static:0;', Context.Empty],
  ['"use strict"; +protected;', Context.Empty],
  ['"use strict"; +public;', Context.Empty],
  ['"use strict"; +yield;', Context.Empty],
  ['"use strict"; +implements:0;', Context.Empty],
  ['"use strict"; +interface:0;', Context.Empty],
  ['"use strict"; +let:0;', Context.Empty],
  ['"use strict"; +package:0;', Context.Empty],
  ['"use strict"; +private:0;', Context.Empty],
  ['"use strict"; +await:0;', Context.Empty],
  ['for(const a = 1;;) c: function b(){}', Context.Empty],
  ['!{ a() { function* b(a = super.c()){} } };', Context.Empty],
  ['({a(b){}} = 0)', Context.Empty],
  ['({a}) = 0;', Context.Empty],
  ['class A { constructor(){} constructor(){} }', Context.Empty],
  ['class A { constructor(){} "constructor"(){} }', Context.Empty],
  ['!class A { constructor(){} constructor(){} }', Context.Empty],
  ['!class A { constructor(){} "constructor"(){} }', Context.Empty],
  ['class A extends B { static get prototype(){} }', Context.Empty],
  ['new.target', Context.Empty],
  ['(class {[super.a](){}});', Context.Empty],
  ['(class {[super()](){}});', Context.Empty],
  ['!{ __proto__: null, __proto__: null, };', Context.Empty],
  ['!{ a() { !function* (a = super.b()){} } };', Context.Empty],
  ['class A extends B { a() { function* f(a = super.b()){} } }', Context.Empty],
  ['class A extends B { a() { !function* (a = super.b()){} } }', Context.Empty]
]);
